### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by illxi** [germinateplatform/germinate-vue#32]
Hello Germinate Team,

I've translated the `en_GB.json` file into Chinese, mainly using OpenAI's translation. Some parts have been manually checked, but due to time constraints, I wasn't able to review everything.

I hope this translation can help make Germinate more accessible to Chinese speakers. 

[zh_CN.json](https://github.com/germinateplatform/germinate-vue/files/13959023/zh_CN.json)

**Comment by sebastian-raubach** [comment]
Hi there,

Thanks a lot for posting this! We're always looking to make Germinate available in more languages.

Creating a translation through AI isn't necessarily ideal without someone going through it and verifying the quality. I appreciate that it's a lot of work to double check the translation, but from our point of view, there's no way to know how good a translation it is since we don't speak Chinese.

If you feel this is something you would be able to do (maybe with the help of some colleagues), we'd invite you to create a pull request against the [Germinate i18n repository](https://github.com/germinateplatform/germinate-i18n).
